### ISSUE TITLE
Very large JS file when using Instant.ofEpochMilli

### ISSUE THREAD

**Issue by migo** [cquiroz/scala-java-time#13]
I noticed that when I want to create the current LocalDate using the following:

    val offset = ZoneOffset.ofHours(0)
    val date = LocalDate.now(clock)

then the generated fastOptJs file is 5.9 MB big. When I instead use 
    
    val date = LocalDate.of(2016,1,1)

then the JS file is only 2.7 MB big and generating it is a lot faster.

I tried to find out what exactly is the cause of this problem and got so far that just including this single line of code has the result of making the JS file bigger:

    val instant = Instant.ofEpochMilli(0)

However, I can't see anything special in the implementation of this method.

I assume that it has something to do with Locales being included in the JS file, since I see many lines like this one in the large version of the generated output only:

```
var xs$53 = new $c_sjs_js_WrappedArray().init___sjs_js_Array([new $c_Llocales_cldr_CurrencyDisplayName().init___T__s_Option("Brazilian New Cruzado (1989\u20131990)", $m_s_None$()), new $c_Llocales_cldr_CurrencyDisplayName().init___T__s_Option("Brazilian new cruzado (1989\u20131990)", new $c_s_Some().init___O("one")), new $c_Llocales_cldr_CurrencyDisplayName().init___T__s_Option("Brazilian new cruzados (1989\u20131990)", new $c_s_Some().init___O("other"))]);
  var this$120 = $m_sci_List$();
  var cbf$53 = this$120.ReusableCBFInstance$2;
  var jsx$502 = new $c_Llocales_cldr_NumberCurrency().init___T__sc_Seq__sc_Seq("BRN", jsx$503, $as_sci_List($s_sc_TraversableLike$class__to__sc_TraversableLike__scg_CanBuildFrom__O(xs$53, cbf$53)));
  var jsx$501 = $m_sci_Nil$();
  $m_sci_List$();
  var xs$54 = new $c_sjs_js_WrappedArray().init___sjs_js_Array([new $c_Llocales_cldr_CurrencyDisplayName().init___T__s_Option("Brazilian Cruzeiro (1993\u20131994)", $m_s_None$()), new $c_Llocales_cldr_CurrencyDisplayName().init___T__s_Option("Brazilian cruzeiro (1993\u20131994)", new $c_s_Some().init___O("one")), new $c_Llocales_cldr_CurrencyDisplayName().init___T__s_Option("Brazilian cruzeiros (1993\u20131994)", new $c_s_Some().init___O("other"))]);
  var this$122 = $m_sci_List$();
  var cbf$54 = this$122.ReusableCBFInstance$2;
  var jsx$500 = new $c_Llocales_cldr_NumberCurrency().init___T__sc_Seq__sc_Seq("BRR", jsx$501, $as_sci_List($s_sc_TraversableLike$class__to__sc_TraversableLike__scg_CanBuildFrom__O(xs$54, cbf$54)));
  var jsx$499 = $m_sci_Nil$(); 
```

**Comment by cquiroz** [comment]
Thanks, I get a different number, around 3.7M but regardless it is very large and indeed the currencies are appearing in the js. Locales uses lazy liberally to reduce the size of the javascript but we may have a bug on the currencies implementation.

Maybe related to https://github.com/cquiroz/scala-java-locales/issues/71

**Comment by cquiroz** [comment]
I can confirm this is a "bug" on locales after the update to include currencies. I'll produce a downgraded version that doesn't include the currency data

**Comment by migo** [comment]
Very nice!
I'm curious how much better the build times/file sizes are now.

**Comment by cquiroz** [comment]
There is a substantial reduction on file size, I haven't measured times but I went from 4M to 1.6M for fastOptJS and 995k to 401k for fullOptJs on scala 2.11.8

**Comment by migo** [comment]
I tested it and the resulting JS file is really smaller and the compile times are much better.

However, when I compile the same code using scalajs-jsjoda (https://github.com/zoepepper/scalajs-jsjoda), the file sizes are still much smaller (2.8 MB compared to 4.2 MB in my case). The good thing is that compile times are nearly identical.
I know that this is not really a fair comparison, since scalajs-jsjoda is very incomplete and does not have support for locales at all.

And there is still a big difference in the file size if I just use

    val date = LocalDate.of(2016, 1, 1)

compared to 

    val date = LocalDate.now(ZoneOffset.ofHours(1))

(2.7 MB compared to 3.6 MB in my case)

So I think that pulling in the Locales is still a bit too heavyweight.
One problem might be that all standard locales defined in java.util.Locale seem to be included in the generated JS file. Is that really necessary or could these also only be loaded on demand?

**Comment by cquiroz** [comment]
the generated file size is a big parameter on the design of locales and fullOptJS should get rid of most of it, so a fair comparison should be done on the basis of fullOptJS. Unfortunately the standard locales are part of the old java API so taking them away would break the API (Though I admit that in most cases it won't affect many people)

But yes, I think we should try to find a way to make loading the files on demand.

Additionally `scala-java-time` has much more functionality and the way the port was made may not be the most efficient in code size terms

After the 2.0.0 release is done we should certainly focus on these issues
