### ISSUE TITLE
Publish artifacts for Scala.js 1.0.0

### ISSUE THREAD

**Issue by dvreeze** [cquiroz/scala-java-time#154]
Scala.js 1.0.0 has been released, so it would be great to publish artifacts for this Scala.js release.

**Comment by cquiroz** [comment]
This is blocked by a bug on Scala.js which should be fixed on 1.0.1

**Comment by dvreeze** [comment]
Thanks for the feedback. Let's hope Scala.js 1.0.1 will arrive soon.

**Comment by aappddeevv** [comment]
Looks like 1.0.1 was just released and. cquiroz, thanks for keeping on top of this with dvreeze.

**Comment by dvreeze** [comment]
Thanks a lot, cquiroz, for releasing scala-java-time 2.0.0-RC5.

**Comment by cquiroz** [comment]
Done on 2.0.0-RC5
