### ISSUE TITLE
Regression test for 2.0.0-RC5

### ISSUE THREAD

**Issue by bwbecker** [cquiroz/scala-java-time#171]
The following tests used to work with dependencies
```
    "io.github.cquiroz" %%% "scala-java-time" % "2.0.0-M13",
    "io.github.cquiroz" %%% "scala-java-time-tzdb" % "2.0.0-M13_2018c", // ToDo: filter timezones
```
but fail with dependencies
```
    "io.github.cquiroz" %%% "scala-java-time" % "2.0.0-RC5",
    "io.github.cquiroz" %%% "scala-java-time-tzdb" % "2.0.0-RC3_2019a", // ToDo: filter timezones
```

```scala
     "with predefined formatters" - {
        "formatFullDate" - {
          assertResult("January 30, 2018") {dt.format(formatFullDate)}
        }
        "formatDayOfWeek" - {
          assertResult("Tuesday Jan. 30") {dt.format(formatDayOfWeek)}
        }
        "formatTime_AM_PM" - {
          assertResult("11:02 AM") {dt.format(formatTime_AM_PM)}
        }
      }
```
where `dt` is defined as `LocalDateTime.of(2018, 1, 30, 11, 2, 45, 750000)`
and the formatters as
```scala
  val formatFullDate = DateTimeFormatter.ofPattern("MMMM dd, yyyy")

  val formatDayOfWeek = DateTimeFormatter.ofPattern("cccc MMM. d")   // Thursday Jan. 25

  val formatTime_AM_PM = DateTimeFormatter.ofPattern("h:mm a")    // 10:15 PM
```

The output I'm now getting from the tests is
```
X oat.xplatform.javaTime.JavaTimeTests.Formatting LocalDateTime.with predefined formatters.formatFullDate 4ms
  utest.AssertionError: utest.assert(actual == expected)
  actual: Any = M01 30, 2018
  expected: T = January 30, 2018
X oat.xplatform.javaTime.JavaTimeTests.Formatting LocalDateTime.with predefined formatters.formatDayOfWeek 3ms
  utest.AssertionError: utest.assert(actual == expected)
  actual: Any = Tue . 30
  expected: T = Tuesday Jan. 30
X oat.xplatform.javaTime.JavaTimeTests.Formatting LocalDateTime.with predefined formatters.formatTime_AM_PM 2ms
  utest.AssertionError: utest.assert(actual == expected)
  actual: Any = 11:02
  expected: T = 11:02 AM
```

I spent some time with the scala-java-time code to see if I could at least write a test, but couldn't get it figured out in a reasonable amount of time.  Sorry.

Thanks for your fantastic work.

**Comment by cquiroz** [comment]
It seems it is defaulting to the root locale. Are you setting your default locale? and did you create a locales db with `sbt-locales`?

**Comment by bwbecker** [comment]
I have not been setting the default locale.  I have not filtered the locales database (yet).

I added a test to check the default locale.  On the JVM side, it's selecting the correct value ("en_CA").  

In the JS tests it fails with just "en" instead of "en_CA".  I added a call to `Locale.setDefault(Locale.CANADA)` to the tests.  The default locale check now passes but two of the three test still fail:

```
      X formatDayOfWeek 3ms
        utest.AssertionError: utest.assert(actual == expected)
        actual: Any = Tuesday Jan.. 30
        expected: T = Tuesday Jan. 30
      X formatTime_AM_PM 2ms
        utest.AssertionError: utest.assert(actual == expected)
        actual: Any = 11:02 a.m.
        expected: T = 11:02 AM
```

Those two tests are:
```
        "formatDayOfWeek" - {
          assertResult("Tuesday Jan. 30") {dt.format(formatDayOfWeek)}
        }
        "formatTime_AM_PM" - {
          assertResult("11:02 AM") {dt.format(formatTime_AM_PM)}
        }
```
where `dt` is `LocalDateTime.of(2018, 1, 30, 11, 2, 45, 750000)`

The first one seems like a bug to me.  The second one is fine either way; it's just different than the way it was.

I'm not sure how to set the default locale on the JS side of things.  Is there initialization code where it will always run?

**Comment by cquiroz** [comment]
Just use `Locale.setDefault(some_locale)`

**Comment by cquiroz** [comment]
I think you need to enable `en_CA` en your db
See this as an example
https://github.com/gemini-hlsw/gemini-locales/

**Comment by bwbecker** [comment]
Thanks for the pointers.  I cloned gemini-locales and got it to publish to my local repo.  Then started making changes to adapt to my situation.  Changing from `localesFilter := LocalesFilter.Selection("en-US")` to use either `en_CA` or `en-CA` causes the following error.  I don't know how to debug it.  Suggestions would be much appreciated.

```
[error] /Users/bwbecker/temp/gemini-locales/target/scala-2.12/src_managed/main/locales/cldr/data/data.scala:10:33: not found: value _en_001
[error] object _en_CA extends LDML(Some(_en_001), LDMLLocale("en", Some("CA"), None, None), None, List(Symbols(latn, None, None, None, None, None, None, None, None, None, Some("e"))), Some(CalendarSymbols(List(), List("Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.", "Jul.", "Aug.", "Sep.", "Oct.", "Nov.", "Dec."), List(), List("Sun.", "Mon.", "Tue.", "Wed.", "Thu.", "Fri.", "Sat."), List("a.m.", "p.m."), List())), Some(CalendarPatterns(Map((0, "EEEE, MMMM d, y"), (1, "MMMM d, y"), (2, "MMM d, y"), (3, "y-MM-dd")), Map((0, "h:mm:ss a zzzz"), (1, "h:mm:ss a z"), (2, "h:mm:ss a"), (3, "h:mm a")))), List(), NumberPatterns(None, None, None))
[error]                                 ^
[error] /Users/bwbecker/temp/gemini-locales/target/scala-2.12/src_managed/main/locales/cldr/data/data.scala:10:33: not found: value _en_001
[error] object _en_CA extends LDML(Some(_en_001), LDMLLocale("en", Some("CA"), None, None), None, List(Symbols(latn, None, None, None, None, None, None, None, None, None, Some("e"))), Some(CalendarSymbols(List(), List("Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.", "Jul.", "Aug.", "Sep.", "Oct.", "Nov.", "Dec."), List(), List("Sun.", "Mon.", "Tue.", "Wed.", "Thu.", "Fri.", "Sat."), List("a.m.", "p.m."), List())), Some(CalendarPatterns(Map((0, "EEEE, MMMM d, y"), (1, "MMMM d, y"), (2, "MMM d, y"), (3, "y-MM-dd")), Map((0, "h:mm:ss a zzzz"), (1, "h:mm:ss a z"), (2, "h:mm:ss a"), (3, "h:mm a")))), List(), NumberPatterns(None, None, None))
```

**Comment by cquiroz** [comment]
Hmm, that seems a bug, locales are hierarchical, the error indicates that the parent of en_CA is not found

**Comment by cquiroz** [comment]
Actually can you try including in selection “en-001” and “en-CA”, as a list

**Comment by bwbecker** [comment]
Thanks.  `localesFilter := LocalesFilter.Selection("en-001", "en-CA")` does not generate the error I noted previously.  Will make further changes and then test.  Thanks again for your wonderful work and support.

**Comment by cquiroz** [comment]
The reason this is happening is that you need to include the whole chain of locales, "en" is always included but if not you'd need to put everything on the chain up to "root". I'll add a few examples to the docs
Thanks for the report

**Comment by bwbecker** [comment]
Just created a pull request with tests that illustrate this issue.

**Comment by cquiroz** [comment]
Can we close this issue?

**Comment by bwbecker** [comment]
Yes.


Byron Weber Becker
School of Computer Science
University of Waterloo  519-888-4567 x34661
bwbecker@uwaterloo.ca
https://cs.uwaterloo.ca/~bwbecker

On Apr 10, 2020, 7:00 PM -0400, Carlos Quiroz <notifications@github.com>, wrote:

Can we close this issue?
