### ISSUE TITLE
OffsetDateTime.now not emitting error anymore, but works wrong

### ISSUE THREAD

**Issue by Daxten** [cquiroz/scala-java-time#20]
Hi,
first of all million thanks for getting tz support out! Dunno if this is really a bug or just a feature which is still missing:

using scalajs OffsetDateTime.now is not throwing an error anymore, but the system default offset seems to be calculated wrong (or not at all?), it will always be +00 as it seems

**Comment by cquiroz** [comment]
Hi, thanks for your kind words

`OffsetDateTime` uses the system default timezone. The system default timezone is kind of undefined on the browser environment so we default to `GMT`. This may not be correct according to the spec but we have to define one

https://github.com/cquiroz/scala-java-time/blob/master/js/src/main/scala/java/util/TimeZone.scala#L10

I think the workaround is to early define a default time zone using `TimeZone.setDefault` but that maybe difficult with the current basic implementation of `TimeZone`. Would that be a viable option for you?

**Comment by Daxten** [comment]
I'm not working so much with timezones, more with the offset so I may not have the best input here..

https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_totimestring

could this help to make, at least, a decision which has the right offset?

**Comment by cquiroz** [comment]
If you know the offset you can do e.g.:

`OffsetDateTime.now(ZoneId.of("GMT-03"))`

**Comment by Daxten** [comment]
So is this then a solution to the problem or why is default not defined like this?:

```
private var default: TimeZone = {
    val d = new Date();
    val n = d.toTimeString();
    val Array(_, tstr) = n.split(" ") 
    new SimpleTimeZone(tstr)
  }
```

**Comment by cquiroz** [comment]
I haven't tried that, So your code reads the browser time and parses the string? Sounds like a good solution to integrate to the project

**Comment by Daxten** [comment]
yes exactly! Cool, is this sth you wanna take a look at or do you need help? I'm working on something different atm but if you don't have time / want to work on different stuff I would try to take a look to bring this forward

**Comment by cquiroz** [comment]
PRs are certainly welcome, I'd appreciate help on this area

**Comment by Daxten** [comment]
#21
