### ISSUE TITLE
It would be nice to get rid of scala-reflect 

### ISSUE THREAD

**Issue by pshirshov** [cquiroz/scala-java-time#206]
Hi,

I'm running my Scala apps on AWS Lambda and there is a very strict limit on classpath jars size. `scala-java-time` is the only library which depends on `scala-reflect`.

From what I can see it should be possible to remove reflection. Could you please consider that?

**Comment by cquiroz** [comment]
Are you using the jvm side of `scala-java-time` in AWS? If so you could use just the std lib implementation

**Comment by pshirshov** [comment]
I need the same code to be executed on AWS under JVM and in user's browser.

So, I'm using `scala-java-time` because of ScalaJS. `scala-java-time` depends on `portable-scala-reflect` which brings `scala-reflect` into my classpath on JVM.

From what I can see you don't provide a "dummy" version of `scala-java-time` for JVM. Am I wrong?

**Comment by cquiroz** [comment]
The general solution for this in sbt is to make only the js side depend on scala-java-time, it is not really needed on the jvm side. e.g.
https://github.com/gemini-hlsw/gsp-math/blob/master/build.sbt#L48

**Comment by pshirshov** [comment]
Yup, seems like that works, thanks.
