### ISSUE TITLE
3.x compilation

### ISSUE THREAD

**Issue by aappddeevv** [cquiroz/scala-java-time#235]
scala-java-time is a dependency for zio and zio now has 3.x support. 

Anyway to add 3.x published supported for scala-java-time? While `withDottyCompat` will probably work, it would be good to get this lib on track for the 3.x series.

Same comment for `scala-java-time-tzb`.

**Comment by cquiroz** [comment]
I'm in the process of porting `scala-java-locales` first to then port `scala-java-time`. There is a macro there which is taking me a while to port

**Comment by aappddeevv** [comment]
It looks like you merged 3.x support so this can probabl ybe closed.

**Comment by cquiroz** [comment]
Yes sorry forgot to close it, version 2.1.0 has scala 3 support
