### ISSUE TITLE
ZoneId.systemDefault not working

### ISSUE THREAD

**Issue by ThijsBroersen** [cquiroz/scala-java-time#35]
I noticed that ```ZoneId.systemDefault``` is not working in javascript, in the jvm it is working fine. My current solution is converting using this:
```
ZoneId.ofOffset(
    Clock.systemDefaultZone.getZone.getId,
    ZoneOffset.ofTotalSeconds((new Date().getTimezoneOffset()) * -60)
```

Does it still need implementation?

**Comment by cquiroz** [comment]
Can you elaborate on why is not working? Did you try the last release 2.0.0-M9

**Comment by ThijsBroersen** [comment]
Yes, I am using the latest version. 
My timezone is GMT+01:00, using the following code in scala-js:
```console.log(ZoneId.systemDefault.toString())
    console.log(LocalDateTime.ofInstant(time, ZoneId.systemDefault).toString())
    console.log(ZoneId.ofOffset(
      Clock.systemDefaultZone.getZone.getId,
      ZoneOffset.ofTotalSeconds((new Date().getTimezoneOffset()) * -60)
    ).toString())
    console.log(LocalDateTime.ofInstant(time, ZoneId.ofOffset(
      Clock.systemDefaultZone.getZone.getId,
      ZoneOffset.ofTotalSeconds((new Date().getTimezoneOffset()) * -60)
    )).toString())```
my result on FireFox and Chrome is:
GMT
2017-03-17T08:28:45.754
GMT+01:00
2017-03-17T09:28:45.754

**Comment by cquiroz** [comment]
I see, `ZoneId` defaults to GMT always on JS. Feel free to send a PR or I'll try to make a fix as soon as possible

**Comment by cquiroz** [comment]
I published a Snapshot: `2.0.0-M10-SNAPSHOT` with a tentative fix. Could you try it?

**Comment by ThijsBroersen** [comment]
I have tried it (after a short search to find the zoneid-fix branch... why the f.. are you using so many branches?!) and it works. However, I am not sure I like the solution with interpolation strings to get the zone-id.. For now I will use my own fix. I have forked the repo will commit to the fork shortly.

**Comment by cquiroz** [comment]
The branches are historical from the original project this one is forked from. I believe I have maybe 1 or 2 that are mine.

Feel free to post a PR. Note that `Clock.systemDefault` delegates all to the same code in `TimeZone`
