### ISSUE TITLE
Publish artifacts for scala-native 0.4.3

### ISSUE THREAD

**Issue by TheElectronWill** [cquiroz/scala-java-time#361]
The most recent artifact for scala-java-time native is [scala-java-time_native0.4_2.13](https://repo1.maven.org/maven2/io/github/cquiroz/scala-java-time_native0.4_2.13)

Would it be possible to publish it for scala-native [0.4.3](https://github.com/scala-native/scala-native/releases/tag/v0.4.3) and scala library 3+? For now I get
```
Error downloading io.github.cquiroz:scala-java-time_native0.4_3:2.3.0
```

**Comment by cquiroz** [comment]
I can publish it

**Comment by plokhotnyuk** [comment]
+1
BTW, Scala Native 0.4.4 is already released

**Comment by cquiroz** [comment]
Did you try v2.4.0-M1?

**Comment by cquiroz** [comment]
Ok. I'll publish 2.4.0-M2 with 0.4.3 and 2.4.0-M3 with 0.4.4
If I get confirmation it is ok I could do a proper 2.4.0

**Comment by cquiroz** [comment]
Had some troubles with the release and had to do only one `2.4.0-M2` with scala-native `0.4.4`. Please let me know if it is working for you

**Comment by plokhotnyuk** [comment]
The latest released version doesn't have Scala Native support for Scala 3.

**Comment by cquiroz** [comment]
Is  scala3 supported by scala native?

**Comment by TheElectronWill** [comment]
yep! [since v0.4.3](https://scala-native.readthedocs.io/en/latest/changelog/0.4.3.html)

**Comment by cquiroz** [comment]
Now I see it was disabled for native
https://github.com/cquiroz/scala-java-time/blob/master/build.sbt#L194

**Comment by TheElectronWill** [comment]
Oh! I guess it's because the [initial support of Scala Native](https://github.com/cquiroz/scala-java-time/commit/a26aaab962abb0861058d9980f97ef777314b4ec) was with v0.4.2, which didn't support Scala3, right?

**Comment by cquiroz** [comment]
Ok, we are kind of stuck. This needs a `scala-java-locales` release which is blocked by `munit` as in https://github.com/scalameta/munit/pull/477

**Comment by TheElectronWill** [comment]
This has now been [merged](https://github.com/scalameta/munit/pull/477#pullrequestreview-937265905) :tada:

**Comment by cquiroz** [comment]
Version 2.4.0 is now out with scala-native support

**Comment by TheElectronWill** [comment]
thanks!
