### ISSUE TITLE
Support for Scala Native

### ISSUE THREAD

**Issue by mkotsbak** [cquiroz/scala-java-time#45]
Hopefully it should be easy to support Scala Native also.

**Comment by cquiroz** [comment]
I don't know much about `scala-native` tooling but it should be possible. There are some `scala.js` specific bits that would need to be ported

**Comment by ekrich** [comment]
You might want to consider creating a version to support only Scala.js and Scala Native. If you put the code in the `java.time` package then code from JVM would port to the two platforms if they have used `java.time`. With the exception of Spark on Scala 2.11 (Java 7), most of the Scala community is on Java 8 anyway.

**Comment by cquiroz** [comment]
The port to `scala-native` is blocked by https://github.com/scala-native/scala-native/issues/1038

**Comment by Andrei-Pozolotin** [comment]
+1

**Comment by ekrich** [comment]
The blocker above has now been closed so the coming release of Scala Native should be supportable.

**Comment by cquiroz** [comment]
Is `portable-scala` running on native? It is used to load locales and tzdb

**Comment by ekrich** [comment]
I believe this is it - https://github.com/scala-native/scala-native/issues/1279

**Comment by avdv** [comment]
Hi.

Since scala-native 0.4.0 has been (unofficially) released, supporting it could be easy... What's the status on this, is there a branch somewhere?

**Comment by cquiroz** [comment]
I tried `native` ages ago, it is probably better to start from scratch

**Comment by avdv** [comment]
OK, thanks. I'll take a look if I have some spare time... (don't hold your breath)

**Comment by cquiroz** [comment]
No problem, on the same vein I don't really have time for this

I think you need to do scala-java-locales first

**Comment by ekrich** [comment]
@cquiroz would you be open to making this a simple Scala Native and Scala.js cross project as long as you can test against the JVM? We could just rename the packages and move things around. It would be much more simple like this - https://github.com/ekrich/sjavatime

**Comment by cquiroz** [comment]
I'm not sure what you mean it is already a scala.js project, I'd expect scala native support to essentially add an extra compilation target

**Comment by ekrich** [comment]
I understand that but I mean simplifying the project to remove all the renaming and changing the packages and such. The reference I gave does Native and JS and tests against JVM but no JVM support for JVMs before there was a `java.time` included.

**Comment by cquiroz** [comment]
I'd like to keep the code in their threetenbp package and rename them on the fly. IDEs get very confused when you try to compile clases in the java space.

**Comment by ekrich** [comment]
Ok, I haven't seen that in Metals but understand.

**Comment by DamianReeves** [comment]
Hi, has development of the scala native support stalled?

**Comment by cquiroz** [comment]
See #346
