### ISSUE TITLE
Scala Native 0.5 release

### ISSUE THREAD

**Issue by MateuszKubuszok** [cquiroz/scala-java-time#504]
Is the release for 0.5 planned anytime soon? With the libraries slowly publishing for it, the lack of scala-java-time for 0.5 would be a blocker for some libraries.

**Comment by plokhotnyuk** [comment]
@cquiroz Could you please publish a release with Scala Native 0.5.3?

I cannot find it in the Maven Central: https://repo1.maven.org/maven2/io/github/cquiroz/scala-java-time_3/

**Comment by sideeffffect** [comment]
https://repo1.maven.org/maven2/io/github/cquiroz/scala-java-time_native0.5_3/2.6.0/

**Comment by plokhotnyuk** [comment]
Thanks a lot to all involved!!!
