### ISSUE TITLE
Deploy scala-java-time 2.0.0-M19 for Scala 2.11

### ISSUE THREAD

**Issue by mdedetrich** [cquiroz/scala-java-time#75]
scala-java-time doesn't appear to be deployed for Scala 2.11 (can't retrieve and dependencies).

**Comment by cquiroz** [comment]
It seems to be deployed at
https://mvnrepository.com/artifact/io.github.cquiroz/scala-java-time_2.11/2.0.0-M13

and
https://mvnrepository.com/artifact/io.github.cquiroz/scala-java-time_sjs0.6_2.11/2.0.0-M13

**Comment by mdedetrich** [comment]
@cquiroz Woops, I meant version 2.0.0-M19, edited title

**Comment by cquiroz** [comment]
Oh, why would you prefer to use an older version?

**Comment by mdedetrich** [comment]
No I want to upgrade to 2.0.0-M19 and I can't because its not deployed for Scala 2.11

**Comment by cquiroz** [comment]
There is no M19, the latest is M13

**Comment by mdedetrich** [comment]
According to maven there is http://search.maven.org/#artifactdetails|io.github.cquiroz|scala-java-time_2.12|2.0.0-M19|

**Comment by cquiroz** [comment]
Weird, It must be a mistake i did is some deployment

**Comment by cquiroz** [comment]
I'm going to close this. the correct version should be at M13
