### ISSUE TITLE
Update tzdb parser

### ISSUE THREAD

**Issue by cquiroz** [cquiroz/scala-java-time#77]
As discussed on gitter

```
@cquiroz I got it to work by setting dbVersion := TzdbPlugin.Version("2018c") - So it seems that the tzdb format has changed in tzdb in 2018{d,e} and your parser somehow does not understand that change.
If you manually start a travis build, I bet that the tests will fail.
```

Thanks @ahjohannessen for reporting this

/cc @ahjohannessen

**Comment by cquiroz** [comment]
I'm trying to reproduce this but it seems I can use newer tzdb versions just fine

**Comment by cquiroz** [comment]
Actually it is a real issue in certain conditions. I'll keep searching the root source

**Comment by cquiroz** [comment]
This is now fixed in `sbt-tzdb`. I'll make a release of `scala-java-time` but you don't need that to get this fixed, it would be enough to update the plugin

**Comment by cquiroz** [comment]
some background:
In tzdb 2018d/e negative DST and save were added for a few european timeo zones, notably  `Europe/Dublin` and a couple of others. Implementations should be able to parse this change but are not forced to use it.

That change broke the parser used in `scala-java-time` and that has been fixed and it is also in use.

The Java side is able to parse the change but it doesn't use it, hence the difference. I can't tell when the java side will be updated if ever (threeten.bp)

IMHO this is safe to upgrade, but I'm unable to test all possible cases

**Comment by ahjohannessen** [comment]
Ok, I see. Thanks for explaining this 👍
