### ISSUE TITLE
Unknown timezone id

### ISSUE THREAD

**Issue by epifab** [cquiroz/scala-java-time#88]
Hi there, thanks for this library!
When I try to run my JS project, I get a "Unknown time-zone ID: Europe/London" exception.
Any idea?

**Comment by cquiroz** [comment]
Most likely you need to add a tzdb using `sbt-tzdb`. Check the documentation at
http://cquiroz.github.io/scala-java-time/

**Comment by epifab** [comment]
hi @cquiroz , yes, adding `sbt-tzbd` fixed it for me. I thought I wouldn't need to as I'm only using `LocalDate` and `LocalDateTime` but apparently I do. thanks again for you answer!
