### ISSUE TITLE
Support timezones using generated code

### ISSUE THREAD

**Issue by cquiroz** [cquiroz/scala-java-time#9]

**Comment by jtcwang** [comment]
Do we have any concrete steps to solve this? I'd like to help make this happen but I'm not sure where to start.

**Comment by cquiroz** [comment]
There are several approaches to give support. The one I'm following is a pure scala.js side.
I wrote a parser for the TZDB data and it can produce scala source files that can be read by a scala.js timezone provider. Some things missing:

* There is a need to massage the data, the basic data read with the parser need to be converted to transition rules that can be used to calculate the dates
* Leap seconds should be parsed and added to the data read
* Tests need to be ported. A great feature of threetenbp is the test suite and I'm porting them to scalatest to make them executable on scala.js
* Reduce data duplication. There is a certain amount or redundant data on the that could be shared across zones
* Reduce data size . The current approach will likely produce a fairly large payload in terms of code size. Given that zones are looked up by name it is difficult for the scala.js optimizer to remove dead data. Some ideas that may help:

1. Store the data in a binary format
2. Filter out zones and epochs that are not needed on a per project basis
3. Provide alternative packages. e.g. data only after 2010

However, I want to asses how by the data is with real numbers once everything is working
* I'd also like to make the providers pluggable somehow if e.g. somebody wants to use momentjs data

I don't know how much of this work is parallelizable but I'd like to complete the data read part and make a release at that moment

**Comment by jtcwang** [comment]
Yeah we need to get scala.js working with timezones as well. Thanks for the detailed summary.

Do you have an idea of how you're going to do the transition rules (algorithm etc) already? If so then we can convert the tests while you work on that. Otherwise we can pickup the timezone transition task.

**Comment by cquiroz** [comment]
The algorithm is not documented anywhere as far as I know. I'm taking the code used on threetenbp tzdb compiler and trying to use that. I'm making some inroads there while at the same time trying to reduce the javaness of the original implementation 😄

**Comment by jtcwang** [comment]
Hmm is that somehow related to moment/moment-timezone/pull/82? Someone mentioned that we can reuse their work for scala-java-time.

For reference, here's the packed and unpacked data https://github.com/moment/moment-timezone/tree/es6/data (definitely different from the binary data from tzdb, not sure what their relationship is)

**Comment by cquiroz** [comment]
I'm not using anything related to moment. I refer to the compiler at
https://github.com/cquiroz/scala-java-time/blob/master/jvm/src/main/scala/org/threeten/bp/zone/TzdbZoneRulesCompiler.scala

**Comment by jtcwang** [comment]
Just to pick your brain: What format will you be compiling it to? At a glance it seems like it's compiling it into a binary format and shipping it with the JAR. How do you think we can make this work for scala.js?

**Comment by cquiroz** [comment]
It won't work as is for sure, the current approach is based on reading serialized objects and rely somewhat on reflection which we cannot do in scala.js. I'm only using the algorithm to process the data from tzdb. My current approach is to generate class instances that can be read quite easily in scala.js. Ideally you'd only get what you need and the optimizer could throw away the unused data but it is not possible as zones are indexed by a String id.

You can check my progress at this branch

https://github.com/cquiroz/scala-java-time/tree/tzdata

Please note that this is work in progress, I may change all/most of it in the upcoming weeks

**Comment by ritschwumm** [comment]
reading this, i just had an idea:

i'm pretty sure in most cases the name of a timezone is coming from a string literal, or at least a constant. which means it's available at compile time for a macro and could be rewritten to e.g. a direct reference to a constant containing the TZ data.

so if someone only ever uses TC names in this restricted way, scala-js _could_ eliminate all the other timezone's data. not sure it's worth the added complexity, though..

**Comment by jtcwang** [comment]
There are many cases where the timezone string is not known at compile time (i.e. user input), so I don't think it'll be worth it.

**Comment by nafg** [comment]
While I agree with @jtcwang, @ritschwumm's suggestion just gave me a weird idea -- maybe instead of trying to parse the tzdb and convert rules into transitions, you could introspect time zone data via the java.time API and generate instances (e.g. still using treehugger) based on that?

**Comment by nafg** [comment]
Just played a bit in ammonite, I think it makes sense. At compile time you can do things like

```scala
ZoneId.getAvailableZoneIds.asScala.map(ZoneId.of(_).getRules.getTransitions.asScala) 
```

**Comment by cquiroz** [comment]
@jtcwang yes I'd think that's true, in principle you can even install your own Zone definitions if you wanted

**Comment by nafg** [comment]
@cquiroz I just want whatever solution will be quickest to ship ;)

**Comment by nafg** [comment]
@cquiroz also isn't there already something to parse tzdb into "running" ZoneTransitions etc.? For some reason I thought there was, just the code might not be under a license you can copy, but that doesn't mean you can't run the code and serialize its "output"...
That would solve the first bullet point.
As for encodings, that's an orthogonal concern.
Last two are subjective so I won't comment but I hope they don't make it take too long :)

**Comment by cquiroz** [comment]
@nafg There is code for parsing in encoding at the `TzdbZoneRulesCompiler` which is licensed under an Apache license. I'm using that as a guide for the conversion but the code is very tangled and side effecting

https://github.com/cquiroz/scala-java-time/blob/master/jvm/src/main/scala/org/threeten/bp/zone/TzdbZoneRulesCompiler.scala

**Comment by cquiroz** [comment]
@nafg About shipping time, I'm actually fairly close to complete my parser (not all code is on github), I just wont commit to an ETA as this is done in my fairly limited free time 😄

**Comment by nafg** [comment]
@cquiroz great news, thanks for the update!
