### ISSUE TITLE
publish for Scala 2.13.0-M5, please?

### ISSUE THREAD

**Issue by SethTisue** [cquiroz/scala-java-time#91]
because over at https://github.com/bkirwi/decline/pull/47 I'm seeing `[error] (declineJS / update) sbt.librarymanagement.ResolveException: unresolved dependency: io.github.cquiroz#scala-java-time_sjs0.6_2.13.0-M5;2.0.0-M13: not found`

**Comment by cquiroz** [comment]
i'll shortly release a new version with 2.13.0-M5 support

**Comment by cquiroz** [comment]
`2.0.0-RC1` has beer released with `2.13.0-M5` support

**Comment by SethTisue** [comment]
🍺
